# Generated by Django 5.1.3 on 2024-11-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=10)),
                ('gubun', models.CharField(max_length=50)),
                ('code_name1', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('hakbun', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=6)),
                ('gubun', models.CharField(blank=True, max_length=50, null=True)),
                ('codeName1', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('hakbun', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
