# Generated by Django 5.1.3 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_form',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('gachucount', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'complain_dv',
            },
        ),
    ]
