# Generated by Django 5.1.2 on 2024-11-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('reserved_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=100)),
                ('mic_status', models.CharField(max_length=50)),
                ('size_satisfaction', models.CharField(max_length=50)),
                ('image_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('has_mic', models.BooleanField()),
                ('has_clock', models.BooleanField()),
                ('has_projector', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reserved', models.BooleanField()),
                ('air_conditioner_status', models.CharField(max_length=50)),
                ('desk_type', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
