# Generated by Django 5.1.3 on 2024-11-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwopgg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('reserved_time', models.DateTimeField()),
                ('place_name', models.CharField(max_length=100)),
                ('image_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('has_mic', models.BooleanField()),
                ('has_projector', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reserved', models.BooleanField()),
                ('desk_type', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mic_status', models.DecimalField(decimal_places=1, max_digits=3)),
                ('clean_status', models.DecimalField(decimal_places=1, max_digits=3)),
                ('air_conditioner_status', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size_satisfaction', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user_id', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='kwopgg.classroominf')),
            ],
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
