# Generated by Django 5.1.3 on 2024-11-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwopgg', '0002_classroominf_classroomreview_delete_classroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassroomInf',
            new_name='classroom_inf',
        ),
        migrations.RenameModel(
            old_name='ClassroomReview',
            new_name='classroom_review',
        ),
    ]
